name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    uses: the-guild-org/shared-config/.github/workflows/ci-node-matrix.yml@main
    with:
      script: pnpm build
      nodeVersions: '[14,16,18]'
      packageManager: pnpm