name: release
on:
  push:
    branches:
      - master

jobs:
  stable:
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    with:
      releaseScript: release
      nodeVersion: 18
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}